### PR TITLE
Stub pa11y response for faster tests

### PR DESCRIPTION
**Pull request by benbalter**

### CODE REVIEW

**Comment by adelevie** [comment]
I'm getting failing tests on `master`, but passing here. FYI.

**Comment by benbalter** [comment]
> I'm getting failing tests on master

Can you provide any more details? [Travis says :recycle:](https://travis-ci.org/benbalter/site-inspector)

**Comment by adelevie** [comment]
```
➜  site-inspector git:(master) ✗ git pull origin master
From github.com:benbalter/site-inspector
 * branch            master     -> FETCH_HEAD
Already up-to-date.
➜  site-inspector git:(master) ✗ bundle exec rake spec 
/Users/alandelevie/.rbenv/versions/2.1.4/bin/ruby -I/Users/alandelevie/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/lib:/Users/alandelevie/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rspec-support-3.2.2/lib /Users/alandelevie/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*/\*_spec.rb --order rand --color

Randomized with seed 64851
...................................................................................FFF..........................................................................

Failures:

  1) SiteInspector::Endpoint::Accessibility with pa11y installed runs the check
     Failure/Error: expect(subject.check).to eql(expected)
     JSON::ParserError:
       757: unexpected token at 'PhantomJS failed to open "http://example.com"
       Error: Page "http://example.com" could not be loaded
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:67:17
           at Proto.apply (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
           at Proto.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
           at D.dnode.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:140:21)
           at D.dnode.write (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:128:22)
           at SockJSConnection.ondata (stream.js:51:26)
           at SockJSConnection.emit (events.js:107:17)
           at Session.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/transport.js:220:25)
           at WebSocketReceiver.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:102:40)
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:75:22
       '
     # ./lib/site-inspector/checks/accessibility.rb:93:in `pa11y'
     # ./lib/site-inspector/checks/accessibility.rb:44:in `check'
     # ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:63:in `block (3 levels) in <top (required)>'

  2) SiteInspector::Endpoint::Accessibility with pa11y installed knows if a site is valid
     Failure/Error: expect(subject.valid?).to eql(true)
     JSON::ParserError:
       757: unexpected token at 'PhantomJS failed to open "http://example.com"
       Error: Page "http://example.com" could not be loaded
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:67:17
           at Proto.apply (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
           at Proto.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
           at D.dnode.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:140:21)
           at D.dnode.write (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:128:22)
           at SockJSConnection.ondata (stream.js:51:26)
           at SockJSConnection.emit (events.js:107:17)
           at Session.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/transport.js:220:25)
           at WebSocketReceiver.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:102:40)
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:75:22
       '
     # ./lib/site-inspector/checks/accessibility.rb:93:in `pa11y'
     # ./lib/site-inspector/checks/accessibility.rb:44:in `check'
     # ./lib/site-inspector/checks/accessibility.rb:40:in `valid?'
     # ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:55:in `block (3 levels) in <top (required)>'

  3) SiteInspector::Endpoint::Accessibility with pa11y installed runs a named check
     Failure/Error: expect(subject.section508).to eql(expected)
     JSON::ParserError:
       757: unexpected token at 'PhantomJS failed to open "http://example.com"
       Error: Page "http://example.com" could not be loaded
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:67:17
           at Proto.apply (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
           at Proto.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
           at D.dnode.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:140:21)
           at D.dnode.write (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:128:22)
           at SockJSConnection.ondata (stream.js:51:26)
           at SockJSConnection.emit (events.js:107:17)
           at Session.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/transport.js:220:25)
           at WebSocketReceiver.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:102:40)
           at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:75:22
       '
     # ./lib/site-inspector/checks/accessibility.rb:93:in `pa11y'
     # ./lib/site-inspector/checks/accessibility.rb:59:in `method_missing'
     # ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:71:in `block (3 levels) in <top (required)>'

Finished in 5.54 seconds (files took 0.41762 seconds to load)
160 examples, 3 failures

Failed examples:

rspec ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:58 # SiteInspector::Endpoint::Accessibility with pa11y installed runs the check
rspec ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:54 # SiteInspector::Endpoint::Accessibility with pa11y installed knows if a site is valid
rspec ./spec/checks/site_inspector_endpoint_accessibility_spec.rb:66 # SiteInspector::Endpoint::Accessibility with pa11y installed runs a named check

Randomized with seed 64851
```

**Comment by benbalter** [comment]
> 'PhantomJS failed to open "http://example.com"

Does `pa11y http://example.com` work for you otherwise?

**Comment by adelevie** [comment]
Nope. Should it? Example.com 404s.

**Comment by adelevie** [comment]
For posterity:

```
$ pa11y http://example.com
Welcome to Pa11y

 > PhantomJS browser created
 > Testing page: "http://example.com"
 > Error: PhantomJS failed to open "http://example.com"
Error: Page "http://example.com" could not be loaded
    at /usr/local/lib/node_modules/pa11y/node_modules/truffler/lib/truffler.js:67:17
    at Proto.apply (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/dnode/lib/dnode.js:128:22)
    at SockJSConnection.ondata (stream.js:51:26)
    at SockJSConnection.emit (events.js:107:17)
    at Session.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/transport.js:220:25)
    at WebSocketReceiver.didMessage (/usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:102:40)
    at /usr/local/lib/node_modules/pa11y/node_modules/truffler/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/trans-websocket.js:75:22

```

**Comment by benbalter** [comment]
> Example.com 404s.

Are you at work? 

```
GET http://example.com

HTTP/1.1 200 OK
Content-Type: text/html
X-Cache: HIT
Server: ECS (dca/24D5)
Expires: Mon, 22 Jun 2015 15:51:53 GMT
Cache-Control: max-age=604800
Date: Mon, 15 Jun 2015 15:51:53 GMT
x-ec-custom-error: 1
Content-Length: 1270
Connection: close
Accept-Ranges: bytes
Etag: "359670651"
Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT

<!doctype html>
<html>
<head>
    <title>Example Domain</title>
```

**Comment by adelevie** [comment]
Yes. Let's pick a federal employee-friendly example URL? :)

**Comment by benbalter** [comment]
> Let's pick a federal employee-friendly example URL? :)

Why in the world would `example.com` be blocked?!?!

**Comment by benbalter** [comment]
Going to merge, since this will fix tests on `master` for you (and remove uncertainty created by network oddities).

**Pull request merged**
